### ISSUE TITLE
pyproject.toml missing

### ISSUE THREAD

**Issue by zepc007** [aoiorio/fastapi-practice#14]

**Comment by aoiorio** [comment]
Thank you for creating the issue.
I think you might be able to see my [pyproject.toml](https://github.com/aoiorio/fastapi-practice/blob/main/README.md?plain=1#L31-L59) in README.md that I added few minutes ago.

Or you can execute [these commands](https://github.com/aoiorio/fastapi-practice/blob/main/README.md?plain=1#L4-L28) that I mentioned in README.md as well.

If you want me to do something. Please let me know.

**Comment by zepc007** [comment]
> Thank you for creating the issue. I think you might be able to see my [pyproject.toml](https://github.com/aoiorio/fastapi-practice/blob/main/README.md?plain=1#L31-L59) in README.md that I added few minutes ago.
> 
> Or you can execute [these commands](https://github.com/aoiorio/fastapi-practice/blob/main/README.md?plain=1#L4-L28) that I mentioned in README.md as well.
> 
> If you want me to do something. Please let me know.

Good work👍
